### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by dustinengle** [dustinengle/bulwark-ui#22]
As a user, I need a checkbox component that will match the style of radio but also allow for validation.  The checkbox should allow for an intermediate state (-) along with (no check) and (check).
- [x] checked state
- [x] unchecked state
- [x] intermediate state [-]
- [ ] validation
- [x] primary
- [x] urgent (red)
- [x] disabled

**Comment by Penple03** [comment]
Not exactly sure what validation means in this context, validation occurs outside of the checkbox component
