### ISSUE TITLE
Amendment: Menu

### ISSUE THREAD

**Issue by padraiq** [dustinengle/bulwark-ui#59]
Current iteration of the top menu requires the following changes

Type:

- 16pt/Roboto/Left (Body)

Function:

- Set invisible bounding box for active area
- Menu should collapse to drop-down list for mobile resolutions
- Resize Hamburger with a max width of 30px, preserve aspect ratio

Animation:

- Simple quick fade to primary on hover

**Comment by dustinengle** [comment]
@padraiq Couple clarifications:
- "Set invisible bounding box for active area" - Which component/section of the drawer?
- "Simple quick fade to primary on hover" - Is that for the text, background, etc?

**Comment by padraiq** [comment]
Sorry,

Bounding box similar to drawer, just to increase the hit-box and save the user having to click on the text.

Fade only for text & icon if we chose to use icons
